"""Initial tables

Revision ID: 08ec42ae3d2a
Revises: 
Create Date: 2026-07-31 19:19:54.534014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ec42ae3d2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('philhealth', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pagibig', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loan', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cash_advance', sa.Float(), nullable=True))
        batch_op.alter_column('gross_income',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('total_deductions',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('net_pay',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.alter_column('net_pay',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_deductions',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('gross_income',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('cash_advance')
        batch_op.drop_column('loan')
        batch_op.drop_column('pagibig')
        batch_op.drop_column('philhealth')
        batch_op.drop_column('sss')

    # ### end Alembic commands ###
