"""Add sil_credits column

Revision ID: 27d66958335e
Revises: 08ec42ae3d2a
Create Date: 2026-08-03 17:31:36.318243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d66958335e'
down_revision = '08ec42ae3d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_results')
    op.drop_table('employee')
    op.drop_table('leave_request')
    op.drop_table('attendance')
    op.drop_table('bulletin')
    op.drop_table('evaluation')
    op.drop_table('holiday')
    op.drop_table('quiz')
    op.drop_table('loan')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sil_credits', sa.Integer(), nullable=True))

    with op.batch_alter_table('leave_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))

    with op.batch_alter_table('loan_history', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])
        batch_op.drop_column('is_paid')

    with op.batch_alter_table('loan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    with op.batch_alter_table('leave_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('sil_credits')

    op.create_table('loan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('date_needed', sa.DATE(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=200), nullable=True),
    sa.Column('approver', sa.VARCHAR(length=100), nullable=True),
    sa.Column('decision_date', sa.DATETIME(), nullable=True),
    sa.Column('date_filed', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=300), nullable=False),
    sa.Column('choice_a', sa.VARCHAR(length=100), nullable=False),
    sa.Column('choice_b', sa.VARCHAR(length=100), nullable=False),
    sa.Column('choice_c', sa.VARCHAR(length=100), nullable=True),
    sa.Column('choice_d', sa.VARCHAR(length=100), nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=1), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holiday',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('evaluator_id', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=200), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulletin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('clock_in', sa.DATETIME(), nullable=True),
    sa.Column('clock_out', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('hours', sa.FLOAT(), nullable=True),
    sa.Column('company', sa.VARCHAR(length=50), nullable=True),
    sa.Column('overtime_hours', sa.FLOAT(), nullable=True),
    sa.Column('is_weekday_ot', sa.BOOLEAN(), nullable=True),
    sa.Column('is_restday_ot', sa.BOOLEAN(), nullable=True),
    sa.Column('is_holiday_ot', sa.BOOLEAN(), nullable=True),
    sa.Column('ot_status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('leave_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('days', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('approver', sa.VARCHAR(length=100), nullable=True),
    sa.Column('decision_date', sa.DATETIME(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('request_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), nullable=True),
    sa.Column('date_filed', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('company', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_no', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('date_started', sa.DATE(), nullable=True),
    sa.Column('sss', sa.VARCHAR(length=50), nullable=True),
    sa.Column('philhealth', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tin', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pagibig', sa.VARCHAR(length=50), nullable=True),
    sa.Column('emergency_contact', sa.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('daily_rate', sa.FLOAT(), nullable=True),
    sa.Column('allowance', sa.FLOAT(), nullable=True),
    sa.Column('incentives', sa.FLOAT(), nullable=True),
    sa.Column('loan_balance', sa.FLOAT(), nullable=True),
    sa.Column('sl_credits', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('total_points', sa.INTEGER(), nullable=False),
    sa.Column('date_taken', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
