"""Initial tables

Revision ID: 95be4a573f77
Revises: 
Create Date: 2026-08-06 15:06:41.879251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95be4a573f77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('date_started', sa.Date(), nullable=True),
    sa.Column('sss', sa.String(length=50), nullable=True),
    sa.Column('philhealth', sa.String(length=50), nullable=True),
    sa.Column('tin', sa.String(length=50), nullable=True),
    sa.Column('pagibig', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('emergency_address', sa.String(length=200), nullable=True),
    sa.Column('sil_credits', sa.Integer(), nullable=True),
    sa.Column('merit_points', sa.Integer(), nullable=True),
    sa.Column('demerit_points', sa.Integer(), nullable=True),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('allowance', sa.Float(), nullable=True),
    sa.Column('incentives', sa.Float(), nullable=True),
    sa.Column('loan_balance', sa.Float(), nullable=True),
    sa.Column('sl_credits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('choice_a', sa.String(length=100), nullable=False),
    sa.Column('choice_b', sa.String(length=100), nullable=False),
    sa.Column('choice_c', sa.String(length=100), nullable=True),
    sa.Column('choice_d', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=True),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('company', sa.String(length=50), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('is_weekday_ot', sa.Boolean(), nullable=True),
    sa.Column('is_restday_ot', sa.Boolean(), nullable=True),
    sa.Column('is_holiday_ot', sa.Boolean(), nullable=True),
    sa.Column('ot_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cutoff_start', sa.Date(), nullable=False),
    sa.Column('cutoff_end', sa.Date(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('rejected_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approver', sa.String(length=100), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('date_filed', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cutoff_start', sa.Date(), nullable=False),
    sa.Column('cutoff_end', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('deductions_applied', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_needed', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('approver', sa.String(length=100), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('date_filed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merit_demerit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('merit_points', sa.Integer(), nullable=True),
    sa.Column('demerit_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payrolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cutoff_start', sa.Date(), nullable=False),
    sa.Column('cutoff_end', sa.Date(), nullable=False),
    sa.Column('gross_income', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=True),
    sa.Column('sss', sa.Float(), nullable=True),
    sa.Column('philhealth', sa.Float(), nullable=True),
    sa.Column('pagibig', sa.Float(), nullable=True),
    sa.Column('loan', sa.Float(), nullable=True),
    sa.Column('cash_advance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redemption_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('points_redeemed', sa.Integer(), nullable=False),
    sa.Column('cash_value', sa.Float(), nullable=False),
    sa.Column('date_redeemed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redemption_history')
    op.drop_table('quiz_results')
    op.drop_table('payrolls')
    op.drop_table('merit_demerit')
    op.drop_table('loans')
    op.drop_table('loan_history')
    op.drop_table('leave_requests')
    op.drop_table('leave_history')
    op.drop_table('evaluations')
    op.drop_table('attendances')
    op.drop_table('quizzes')
    op.drop_table('holidays')
    op.drop_table('employees')
    op.drop_table('bulletins')
    # ### end Alembic commands ###
